# Generated by Django 5.2.17 on 2026-08-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise", models.CharField(max_length=100)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reps", models.PositiveIntegerField()),
                ("sets", models.PositiveIntegerField()),
                ("workout_date", models.DateField()),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
